### ISSUE TITLE
Gem version on rubygems is outdated

### ISSUE THREAD

**Issue by bear-in-mind** [leastbad/all_futures#12]
Hey there !
First, thanks for this awesome library. Just to point out that the version hosted on rubygems is outdated and no longer works. Had to manually point to the repo. No big deal, but I thought you should know.
Cheers

**Comment by leastbad** [comment]
It's true!

I've got a funny one for you: technically, this gem isn't released yet.

I know! It's a bit of a farce at this late stage. However, development is halted on v2, which is to be the first release, until StimulusReflex 3.5 ships in the next little bit.

Everything takes longer than you think it will, despite best intentions. In the meantime, master branch is the way to go!

**Comment by bear-in-mind** [comment]
Haha love this. Well, let's (eagerly) wait for those, then :)
Good luck on the last few miles 💪
